/**
 * Core data model for Chat Vault Operator.
 *
 * IMPORTANT INVARIANT: no field in this model may ever hold ChatGPT conversation
 * body text. Only metadata that is visible on the sidebar (title, link) plus
 * locally-authored bookkeeping fields are permitted.
 */

export const REFLECTION_STATUSES = [
  'unreviewed',
  'reflection_required',
  'reflected',
  'not_required',
] as const;

export type ReflectionStatus = (typeof REFLECTION_STATUSES)[number];

export const ARCHIVE_STATUSES = [
  'active',
  'candidate',
  'approved',
  'archive_requested',
  'archive_observed',
  'reconciliation_required',
] as const;

export type ArchiveStatus = (typeof ARCHIVE_STATUSES)[number];

/**
 * A single tracked conversation.
 *
 * `title` is the sidebar label, which is a summary generated by ChatGPT, not
 * conversation content. It is retained because the operator needs it to make
 * archive decisions. Everything else is either an identifier or local state.
 */
export interface ConversationRecord {
  conversation_id: string;
  url: string;
  title: string;
  /** ISO-8601, or null when the sidebar does not expose it. */
  created_at: string | null;
  updated_at: string | null;
  /** Canonical ChatGPT project (gizmo) id, e.g. `g-p-<32hex>`, or null. */
  project_id: string | null;
  reflection_status: ReflectionStatus;
  /** Vault note path, GitHub issue URL, ticket id, ... Free text, local only. */
  reflection_reference: string | null;
  /** Short operator memo about what was reflected. Never conversation text. */
  reflection_summary: string | null;
  reflection_completed_at: string | null;
  archive_status: ArchiveStatus;
  approved_at: string | null;
  archived_at: string | null;
  last_observed_at: string | null;
  operation_attempts: number;
  error_code: string | null;
  error_message: string | null;
}

/** Exhaustive list of persisted keys. Used by the import validator. */
export const CONVERSATION_RECORD_KEYS = [
  'conversation_id',
  'url',
  'title',
  'created_at',
  'updated_at',
  'project_id',
  'reflection_status',
  'reflection_reference',
  'reflection_summary',
  'reflection_completed_at',
  'archive_status',
  'approved_at',
  'archived_at',
  'last_observed_at',
  'operation_attempts',
  'error_code',
  'error_message',
] as const;

/**
 * What the content script reports after reading the sidebar DOM.
 * Deliberately narrower than ConversationRecord: the DOM layer never invents
 * local bookkeeping state.
 */
export interface ObservedConversation {
  conversation_id: string;
  url: string;
  title: string;
  project_id: string | null;
  /** Sidebar bucket heading such as "Today" / "Previous 7 days", when present. */
  date_bucket: string | null;
  /** ISO-8601 timestamp derived from the bucket, when derivable. */
  created_at: string | null;
  observed_at: string;
}

/** A sidebar link the content script could not turn into a usable identity. */
export interface UnidentifiedLink {
  href: string;
  title: string;
  reason: 'no_conversation_id' | 'unsupported_url';
}

export interface ScanResult {
  conversations: ObservedConversation[];
  unidentified: UnidentifiedLink[];
  /** conversation_id of the conversation the tab is currently displaying. */
  active_conversation_id: string | null;
  scanned_at: string;
}

export const OPERATION_LOG_TYPES = [
  'scan',
  'reflection_updated',
  'candidate_added',
  'candidate_removed',
  'approved',
  'approval_rejected',
  'approval_revoked',
  'dry_run',
  'import',
  'import_rejected',
  'export',
  'log_cleared',
] as const;

export type OperationLogType = (typeof OPERATION_LOG_TYPES)[number];

export interface OperationLogEntry {
  id: string;
  at: string;
  type: OperationLogType;
  /** Affected conversation, when the action targets exactly one. */
  conversation_id: string | null;
  /** Short human-readable detail. Must never contain conversation body text. */
  detail: string;
}
